version: '2'
services:
  api:
    build: ./api
    environment:
      - ENV="development"
    ports:
      - "3000:8080"

  frontend:
    build: ./frontend
    environment:
      - NODE_ENV="development"
    ports:
      - "5000:3000"
    volumes:
      - ./frontend/app/src:/app/src 
