version: '2'
services:
  api:
    build:
      context: ./api
      args:
        app_env: ${APP_ENV}
    volumes:
      - ./api:/go/src/github.com/McMenemy/sequentify/api
    ports:
      - "3000:8080"

  frontend:
    build:
      context: ./frontend
      args:
        app_env: ${APP_ENV}
    volumes:
      - ./frontend/app/src:/app/src 
    ports:
      - "5000:3000"
